import { ResolverManifest } from "pixi.js";

export const manifest: ResolverManifest = {
    bundles: [
        {
            name: "songGame",
            assets:
            {
                // FONT
                Montserrat: "./Montserrat-ExtraBold.ttf",

                // IMAGES
                NivelCompletado: "./images/nivelcompletado.png",
                Rayo: "./images/rayo.gif",
                SoundWave: "./images/soundwave.gif",
                Next: "./images/next.svg",
                Rayo2: "./images/rayo2.svg",
                BackArrow: "./images/backarrow.svg",
                Cinta: "./images/cinta.png",
                Star: "./images/star.png",
                Star2: "./images/star2.png",
                LevelSelectorBanner: "./images/levelselectorbanner.png",
                TitleLogo: "./images/titlelogo.png",
                TitleBackground: "./images/titlebackground.jpg",
                QuizBackground: "./images/quizbackground.jpg",
                BlackWall: "./images/blackwall.jpg",
                BlackPaper: "./images/blackpaper.jpg",
                
                // SOUNDS
                Cheer: "./sounds/cheer.mp3",
                Pip: "./sounds/pip.mp3",
                Guitar: "./sounds/guitar.mp3",
                Correct: "./sounds/correct.mp3",
                Wrong: "./sounds/wrong.mp3",

                // SONGS
                Song0: "./songs/song0.mp3",
                Song1: "./songs/song1.mp3",
                Song2: "./songs/song2.mp3",
                Song3: "./songs/song3.mp3",
                Song4: "./songs/song4.mp3",
                Song5: "./songs/song5.mp3",
                Song6: "./songs/song6.mp3",
                Song7: "./songs/song7.mp3",
                Song8: "./songs/song8.mp3",
                Song9: "./songs/song9.mp3",
                Song10: "./songs/song10.mp3",
                Song11: "./songs/song11.mp3",
                Song12: "./songs/song12.mp3",
                Song13: "./songs/song13.mp3",
                Song14: "./songs/song14.mp3",
                Song15: "./songs/song15.mp3",
                Song16: "./songs/song16.mp3",
                Song17: "./songs/song17.mp3",
                Song18: "./songs/song18.mp3",
                Song19: "./songs/song19.mp3",
                Song20: "./songs/song20.mp3",
                Song21: "./songs/song21.mp3",
                Song22: "./songs/song22.mp3",
                Song23: "./songs/song23.mp3",
                Song24: "./songs/song24.mp3",
                Song25: "./songs/song25.mp3",
                Song26: "./songs/song26.mp3",
                Song27: "./songs/song27.mp3",
                Song28: "./songs/song28.mp3",
                Song29: "./songs/song29.mp3",
                Song30: "./songs/song30.mp3",
                Song31: "./songs/song31.mp3",
                Song32: "./songs/song32.mp3",
                Song33: "./songs/song33.mp3",
                Song34: "./songs/song34.mp3",
                Song35: "./songs/song35.mp3",
                Song36: "./songs/song36.mp3",
                Song37: "./songs/song37.mp3",
                Song38: "./songs/song38.mp3",
                Song39: "./songs/song39.mp3",

                // ALBUM COVERS
                ImgSong0: "./songs/song0.jpg",
                ImgSong1: "./songs/song1.jpg",
                ImgSong2: "./songs/song2.jpg",
                ImgSong3: "./songs/song3.jpg",
                ImgSong4: "./songs/song4.jpg",
                ImgSong5: "./songs/song5.jpg",
                ImgSong6: "./songs/song6.jpg",
                ImgSong7: "./songs/song7.jpg",
                ImgSong8: "./songs/song8.jpg",
                ImgSong9: "./songs/song9.jpg",
                ImgSong10: "./songs/song10.jpg",
                ImgSong11: "./songs/song11.jpg",
                ImgSong12: "./songs/song12.jpg",
                ImgSong13: "./songs/song13.jpg",
                ImgSong14: "./songs/song14.jpg",
                ImgSong15: "./songs/song15.jpg",
                ImgSong16: "./songs/song16.jpg",
                ImgSong17: "./songs/song17.jpg",
                ImgSong18: "./songs/song18.jpg",
                ImgSong19: "./songs/song19.jpg",
                ImgSong20: "./songs/song20.jpg",
                ImgSong21: "./songs/song21.jpg",
                ImgSong22: "./songs/song22.jpg",
                ImgSong23: "./songs/song23.jpg",
                ImgSong24: "./songs/song24.jpg",
                ImgSong25: "./songs/song25.jpg",
                ImgSong26: "./songs/song26.jpg",
                ImgSong27: "./songs/song27.jpg",
                ImgSong28: "./songs/song28.jpg",
                ImgSong29: "./songs/song29.jpg",
                ImgSong30: "./songs/song30.jpg",
                ImgSong31: "./songs/song31.jpg",
                ImgSong32: "./songs/song32.jpg",
                ImgSong33: "./songs/song33.jpg",
                ImgSong34: "./songs/song34.jpg",
                ImgSong35: "./songs/song35.jpg",
                ImgSong36: "./songs/song36.jpg",
                ImgSong37: "./songs/song37.jpg",
                ImgSong38: "./songs/song38.jpg",
                ImgSong39: "./songs/song39.jpg"
            }
        },
    ]
}